<? if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?}?>
<!-- fixed items -->
    <table id="page_position">
        <tr>
            <td>
                <table id="centerpage_shell" align="center">
                    <tr>
                        <td>
                            <table id="videoplayer">
                                <tr>
                                    <td>
                                        <div id="videoplayer_title"></div>
                                        <div id="videoplayer_content">
                                            <iframe width="320" height="240" src="//www.youtube.com/embed/tj1m1Mg-kS4?rel=0" frameborder="0" allowfullscreen></iframe>
                                        </div>
                                        <div id="videoplayer_footer">
                                            <p id="videoplayer_text">Already have a PEplanning Account? <a href="javascript:void(0);" onclick="javascript:showOverlay('Login');">Sign in!</a></p>
                                        </div> 
                                      <iframe width="3420" height="265" src="//www.youtube.com/embed/tj1m1Mg-kS4" frameborder="0" allowfullscreen></iframe>
                                    </td>
                                </tr>                                
                            </table>
                            <table id="register_btn">
                                <tr>
                                <td>
                                        <a href="https://<?php echo $_SERVER['HTTP_HOST']?>/auth/subscribe"><span>register button</span></a>
                                    </td>
                                </tr>
                            </table>
                                                        
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
<!-- end of fixed items -->

<div id="main_feature">
        <!-- slides -->        
        <div class="scrollable" id="scroller">
            <div id="left_grad"></div>
            <div class="items">                
                <div id="slide1">
                    <a id="link_poster_homepage" href="/createaplan" style="color:#1aa6ab; text-decoration:underline;"><span>5 step planning processin</span></a>
                    <div id="slide1_content">
                        <div id="slide1_learnmore" class="learnmore"><a href="/aboutus"><span>learn more</span></a></div>
                        
                        <!-- For IE7 only -->
                        <div id="get_started" class="ie7">
                            <table id="register_btn">
                                <tr>
                                    <td>
                                <td>
                                        <a href="https://<?php echo $_SERVER['HTTP_HOST']?>/auth/subscribe"><span>register button</span></a>
                                    </td>
                                </tr>
                            </table>
                            <table id="videoplayer">
                                <tr>
                                    <td>
                                        <div id="videoplayer_title"></div>
                                        <div id="videoplayer_content">
                                            <p id="videoplayer_learnmore"><a href="/resources/dinnertime-delighters"><span>See More</span></a></p>
                                        </div>
                                        <div id="videoplayer_footer">
                                            <p id="videoplayer_text">Already have a PEplanning Account? <a href="javascript:void(0);" onclick="javascript:showOverlay('Login');">Sign in!</a></p>
                                        </div>
                                    </td>
                                </tr>                                
                            </table></div>
                        <!-- end IE7 only -->
                    </div>
                </div>
                
            </div>
            <div id="right_grad"></div>
        </div>        
        <br clear="all" />            
        <div id="feature_arrows">
            <div id="arrow_left" class="prev browse left"><span>left</span></div>
            <div id="arrow_right" class="next browse right"><span>right</span></div>
        </div>
</div>    
