<?php if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?php }?>
		<div id="navWrap">
            <div id='nav' class='header'>
                <span><a href='#about'>ABOUT</a></span>
                <span><a href='#how'>HOW IT WORKS</a></span>
                <span><a href='#connect'>CONNECT</a></span>
                <span><a href='#price'>PRICING</a></span>
                <span><a href='/auth/signup?process=1' style='color:#fb5502;'>TRIAL</a></span>
                <span><a href='#somesay'>RECOMMENDATION</a></span>
                <span><a href='/auth/schoolsignup'>BUY</a></span>
                <span><a href='#faq'>FAQ</a></span>
                <span><a href='#contact'>CONTACT</a></span>
                <span><a href='/blog'>blog</a></span>
                  
            </div>
        </div>
        <div class='logo'>
            <a href='/'><img border=none src="/img/signup_logo.png"></a>
            </div>  
		<div class='content'>
        	<?php echo $this->response;?>
        </div>
