<?php 
include_once("recaptchalib.php");
$privatekey = "6LdQmPESAAAAAIYhvd1X3piy5s06tifVD2Ds0ROt";
$confirm=$this->confirm;
if($_GET['process']) $tab_selected=$_GET['process']; else $tab_selected=0;
if($this->process) $tab_selected=$this->process;?>
<script>
var RecaptchaOptions = {
    theme : 'clean'
 };
 </script>
<div id='signup-box' class='centred'>
	<div id='signup-logo'>
    </div>
    <div id='signup-div'>
    	<a href='/'><img border=none src="/img/signup_logo.png"></a>
    	<div id='signup-form-container'>
        <ul class='signup-tabs'>
        	<li><a class='signon-color' href='#password'>Password</a></li>
            <li><a class='signup-color' href='#username'>Username</a></li>
        </ul>
        <div class='signup-panes'>
        	<div>
          		<form id='signup-form' name='signup-form' method="post" action='/auth/changecredentials'>
                <input id='signup_name' name='signup_name' type="text" size=128
                 <?php if(($this->values['signup_name'])&&($this->values['signup_name']!='username')) echo "value='".$this->values['signup_name']."'."; 
				 	   else echo "value='username' onblur='if(this.value==\"\")this.value=\"username\";$(\"#signup_name_hint\").html(\"\")' onfocus='if(this.value==\"username\")this.value=\"\";$(\"#signup_name_hint\").html(\"Enter your username\")'";?>
                      />
                <label class='signup' id='signup_name_hint'>
                <?php if(($this->response['result']==10)||($this->response['result']==11)) echo $this->response['detail']?>
                </label>
          		<input id='signup_0_password' name='signup_0_password' type='password' size=128 onblur='passwordBlur("signup_0");$("#signup_0_password_hint").html("")' 
				<?php if(($this->values['signup_0_password'])&&($this->values['signup_0_password']!='password'))
							{ echo "value='".$this->values['signup_0_password']."' style=\'display: inline;\'";}  
					  else 
					  		{ echo "value='' style='display: none;'";}?>
                      />
                <input id="signup_0_password_clear" name='signup_0_password_clear' type="text" onfocus='passwordFocus("signup_0");$("#signup_0_password_hint").html("Enter your current password")' 
                <?php if(($this->values['signup_0_password'])&&($this->values['signup_0_password']!='password'))
							{ echo "style='display: none;'";}
					  else 
					  		{ echo "value='password' style='display: inline;'";}
					  //if($this->response['result']==2) echo ' class=\'form-error\''?>
                      />
                <label class='signup' id='signup_0_password_hint'>
                <?php if(($this->response['result']==10)||($this->response['result']==11)) echo $this->response['detail']?>
                </label>
          		<input id='signup_1_password' name='signup_1_password' type='password' size=128 onblur='passwordBlur("signup_1");$("#signup_1_password_hint").html("")' 
				<?php if(($this->values['signup_1_password'])&&($this->values['signup_1_password']!='new password'))
							{ echo "value='".$this->values['signup_1_password']."' style=\'display: inline;\'";}  
					  else 
					  		{ echo "value='' style='display: none;'";}?>
                      />
                <input id="signup_1_password_clear" name='signup_1_password_clear' type="text" onfocus='passwordFocus("signup_1");$("#signup_1_password_hint").html("Enter your new password")' 
                <?php if(($this->values['signup_1_password'])&&($this->values['signup_1_password']!='new password'))
							{ echo "style='display: none;'";}
					  else 
					  		{ echo "value='new password' style='display: inline;'";}
					  //if($this->response['result']==2) echo ' class=\'form-error\''?>
                      />
                <label class='signup' id='signup_1_password_hint'>
                <?php if(($this->response['result']==10)||($this->response['result']==12)||($this->response['result']==13)) echo $this->response['detail']?>
                </label>
          		<input id='signup_2_password' name='signup_2_password' type='password' size=128 onblur='passwordBlur("signup_2");$("#signup_2_password_hint").html("")' 
				<?php if(($this->values['signup_2_password'])&&($this->values['signup_2_password']!='confirm password'))
							{ echo "value='".$this->values['signup_2_password']."' style=\'display: inline;\'";}  
					  else 
					  		{ echo "value='' style='display: none;'";}?>
                      />
                <input id="signup_2_password_clear" name='signup_2_password_clear' type="text" onfocus='passwordFocus("signup_2");$("#signup_2_password_hint").html("Re-Enter your new password")' 
                <?php if(($this->values['signup_2_password'])&&($this->values['signup_2_password']!='confirm password'))
							{ echo "style='display: none;'";}
					  else 
					  		{ echo "value='confirm password' style='display: inline;'";}
					  //if($this->response['result']==2) echo ' class=\'form-error\''?>
                      />
                <label class='signup' id='signup_2_password_hint'>
                <?php if(($this->response['result']==10)||($this->response['result']==12)||($this->response['result']==13)) echo $this->response['detail']?>
                </label>
                <input type='submit' id='change' name='change' class='password'
                 <?php if($this->response['result']!=1) echo "value='Try Again'";
					  else echo "value='Change'";?>
                 />
                 <input type="hidden" id="changing" name="changing" value="password" />
                </form>
                <a class='change-text signon-color' href="/index/index#contact">Unsure about anything? Get in touch</a>
                <div class='changecredentials-password-information'>
        		<p class='changecredentials-password-color'>You are about to change your password. Simply enter your <span class="signon-bold">username, current password and new password</span> and we will make the change for you</p>
        	</div>
            </div>
            	
            <div>
            	<form id='signup-form' name='signup-form' method="post" action='/auth/changecredentials'>
                <input id='signup_name' name='signup_name' type="text" size=128
                 <?php if(($this->values['signup_name'])&&($this->values['signup_name']!='username')) echo "value='".$this->values['signup_name']."'."; 
				 	   else echo "value='username' onblur='if(this.value==\"\")this.value=\"username\";$(\"#signup_username_hint\").html(\"\")' onfocus='if(this.value==\"username\")this.value=\"\";$(\"#signup_username_hint\").html(\"Enter your username\")'";?>
                      />
                <label class='signup' id='signup_username_hint'>
                <?php if(($this->response['result']==20)||($this->response['result']==21)) echo $this->response['detail']?>
                </label>
          		
          		<input id='signup_3_password' name='signup_3_password' type='password' size=128 onblur='passwordBlur("signup_3");$("#signup_3_password_hint").html("")' 
				<?php if(($this->values['signup_3_password'])&&($this->values['signup_3_password']!='password'))
							{ echo "value='".$this->values['signup_3_password']."' style=\'display: inline;\'";}  
					  else 
					  		{ echo "value='' style='display: none;'";}?>
                      />
                <input id="signup_3_password_clear" name='signup_3_password_clear' type="text" onfocus='passwordFocus("signup_3");$("#signup_3_password_hint").html("Enter your chosen password")' 
                <?php if(($this->values['signup_3_password'])&&($this->values['signup_3_password']!='password'))
							{ echo "style='display: none;'";}
					  else 
					  		{ echo "value='password' style='display: inline;'";}
					  //if($this->response['result']==2) echo ' class=\'form-error\''?>
                      />
                <label class='signup' id='signup_3_password_hint'>
                <?php if(($this->response['result']==20)||($this->response['result']==21)) echo $this->response['detail']?>
                </label>
          		<input id='signup_email' name='signup_email' type="text" size=128
                 <?php if(($this->values['signup_email'])&&($this->values['signup_email']!='email address')) echo "value='".$this->values['signup_email']."'"; 
				 	   else echo "value='email address' onblur='if(this.value==\"\")this.value=\"email address\";$(\"#signup_email_hint\").html(\"\")' onfocus='if(this.value==\"email address\")this.value=\"\";$(\"#signup_email_hint\").html(\"Enter your email address\")'";?>
                      />
                <label class='signup' id='signup_email_hint'>
                <?php if(($this->response['result']==20)||($this->response['result']==22)||($this->response['result']==23)) echo $this->response['detail']?>
                </label>
                <input type='submit' id='change' name='change' class='username'
				<?php if($this->response['result']!=1) echo "value='Try Again'";
					  else echo "value='Change'";?>
                />
                <input type="hidden" id="changing" name="changing" value="username" />
                </form>
                <a class='change-text signup-color' href="/index/index#contact">Unsure about anything? Get in touch</a>
                <div class='changecredentials-username-information'>
        		<p class='changecredentials-username-color'>You are about to change your old username for an email address. Simply enter your <span class="signon-bold">username, password and email address</span> and we will make the change for you</p>		
        		</div>
            </div>
    	</div>
        
    </div>
</div>
<script>
var signUpTabs = $("ul.signup-tabs").tabs("div.signup-panes > div",
					{initialIndex:<?php echo $tab_selected;?>
					});
</script>
