<?php 
if($_GET['change']) $change=$_GET['change'];
if($this->change) $change=$this->change;?>

<div id='signup-box' class='centred'>
	<div id='signup-logo'>
    </div>
    <div id='signup-div'>
    	<a href='/'><img border=none src="/img/signup_logo.png"></a>
    	<div id='signup-form-container'>
        	<div class='changecredentialssuccess-<?php echo $change?>-information'>
              <p class='changecredentialssuccess-<?php echo $change?>-color'>You just updated the <?php echo $change?> for <?php echo $this->email_address?></p>
              <p class='changecredentialssuccess-<?php echo $change?>-color'>We have emailed you confirmation</p>
              <p class='changecredentialssuccess-<?php echo $change?>-color'>Click <a href="/">here</a> to go to the home page</p>
              <p class='changecredentialssuccess-<?php echo $change?>-color'>click <a href="/auth/signup?process=0">here </a>to sign in with your new credentials</p>
         	</div>
        </div>
    </div>
</div>
