<div class="learn_content">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        
                    </td>
                    <td valign="top" id="learn_text" style="margin-left:20px;">
                        <div id="content">
                            <div id="learn_content">
                                <div id="reactivate">
                                    <table id="reactivate_content">
                                        <tr>
                                            <td valign="top">
                                                <div>
                                                    <h2><?php echo $this->detail ?></h2>
                                                    <?php if($this->result==1){?>
                                                            <h2>Returning you to the home page now....</h2>
                                                    <?php }?>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                       </div>
                    </td>
                    <td id="right_section" valign="top">
                        
                    </td>
                </tr>
            </table>
        </div>
<?php if($this->result==1){?>
<META http-equiv="refresh" content="5;URL=http://<?php echo $_SERVER['HTTP_HOST']?>/">
<?php }?>