<div id='signup-box' class='centred'>
	<div id='signup-logo'>
    </div>
    <div id='signup-div'>
    	<a href='/'><img border=none src="/img/signup_logo.png"></a>
    	<div id='signup-form-container'>
        <ul class='signup-tabs'>
        	<li><a class='signon-color' href='#signon'>Reset Password</a></li>
            <li><a class='signup-color' href='#signup'></a></li>
        </ul>
        <div class='signup-panes'>
        	<div>
          		<form id='signup-form' name='signup-form' method="post" action='/auth/password-reset'>
          		<input id='signup_email' name='signup_email' type="text" size=128
                 <?php if(($this->values['signup_email'])&&($this->values['signup_email']!='email address')) echo "value='".$this->values['signup_email']."'"; 
				 	   else echo "value='email address' onblur='if(this.value==\"\")this.value=\"email address\";$(\"#signon_email_hint\").html(\"\")' onfocus='if(this.value==\"email address\")this.value=\"\";$(\"#signon_email_hint\").html(\"Enter your email address\")'";?>
                      />
                <label class='signup' id='signon_email_hint'>
                <?php if(($this->response['result']==10)||($this->response['result']==12)||($this->response['result']==13)) echo $this->response['detail']?>
                </label>
          		<input id='signup_email_confirm' name='signup_email_confirm' type="text" size=128
                 <?php if(($this->values['signup_email_confirm'])&&($this->values['signup_email_confirm']!='confirm email address')) echo "value='".$this->values['signup_email_confirm']."'"; 
				 	   else echo "value='confirm email address' onblur='if(this.value==\"\")this.value=\"confirm email address\";$(\"#signon_email_confirm_hint\").html(\"\")' onfocus='if(this.value==\"confirm email address\")this.value=\"\";$(\"#signon_email_confirm_hint\").html(\"Re-enter your email address\")'";?>
                      />
                <label class='signup' id='signon_email_confirm_hint'>
                <?php if(($this->response['result']==10)||($this->response['result']==11)) echo $this->response['detail']?>
                </label>
                <input type='submit' id='signup' name='signup' class='signon'
                <?php if($this->response['result']!=1) echo "value='Try Again'";
					  else echo "value='Reset'";?>
                />
                </form>
                <div class='reset-information'>
        		<p class='signon-color'>You are requesting a reset of your <span class="signon-bold">password</span> a new password will be sent to the <span class="signon-bold">email</span> you enter here</p>	
        	</div>
            </div>
            
            <div>
            	
            </div>
          	
    	</div>
        
    </div>
</div>
<script>
var signUpTabs = $("ul.signup-tabs").tabs("div.signup-panes > div",
					{initialIndex:0
					});
</script>
