<?php 
if($_GET['process']) $process=$_GET['process'];
if($this->process) $process=$this->process;?>

<div id='school-signup-box' class='centred'>
	<div id='school-signup-div'>
    	<img border=none src="/img/Register Step Complete.png" usemap="#Map" />
          <map name="Map" id="Map">
              <area alt="" title="" href="http://<?php echo  $_SERVER['HTTP_HOST']?>/" shape="rect" coords="415,4,647,117" />
              <area alt="" title="" href="https://twitter.com/PEplanning" shape="rect" coords="705,848,752,890" />
              <area alt="" title="" href="http://www.pinterest.com/peplanning/" shape="rect" coords="779,850,824,897" />
              <area alt="" title="" href="http://peplanning.tumblr.com/" shape="rect" coords="843,851,885,898" />
              <area alt="" title="" href="https://www.youtube.com/user/peplanning" shape="rect" coords="902,852,964,903" />
              <area alt="" title="" href="https://www.facebook.com/PEplanning" shape="rect" coords="968,854,1035,904" />
          </map>
        </div>
    </div>
</div>
