<?php if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?php }?>
<!--<div id="staffroom_welcome">
        <div id="staffroom_welcome_content">
            <span>Hi
                    <?php if ($this->level==0){?>
                        <a href='javascript:void(0)'><b><?php echo $this->username?></b></a>, you are visiting</span>
                    <?php }
                    elseif (($this->level>=1)&&($this->level<=5)) {?>
                        <a href='javascript:void(0)' onclick="javascript:editUser(<?php echo $this->id?>)"><b><?php echo $this->username?></b></a>, you are signed in</span>
                       <?php }
                       else {?>
                        <a href='/tplan/DB_Maintenance'><b><?php echo $this->username?></b></a>, you are signed in</span>
            <?php }?>
            <?php if (($this->level>=5)){?>
            <div id="badge_staffroom">
                <a href="/staffroom"><span>Back to the PEplanning Staffroom</span></a>
            </div>
            <?php }?>
            </div>
    </div>--> 
<div id="resources">
        <table class="stage">
            <tr>
                <td colspan="3">
                    <div class="resources_backlink"><a href="/resources"><span>back to Additional Resources</span></a></div>
                    <div id="resources_title">
                        <div id="resources_img_title_dance"><span>Dance Resources</span></div>
                        
                    </div>
                </td>
            </tr>
            <tr>
                <td id="resources_left_section" valign="top">
                    <a id="resources_img_dance" class="resources_img_display"><span>Dance Resources</span></a>
                    <a id="resources_img_dance" class="resources_img_display"><span>Dance Resources</span></a>
                    </td>
                <td id="left_section_spacing"></td>
                <td id="middle_section" valign="top">
                     <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle">Street Dance - Rather Be</span></p>
                        <span class="resources_midsection_desc"><p>Street Dance - Rather Bet</p><a href="javascript:void(0)" onclick="downloadFile('DanceYear3.zip',<?php echo $this->level?>)">Download resource (.zip)</a></span>
                    </div>
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle">Street Dance - Olympic Games</span></p>
                        <span class="resources_midsection_desc"><p>Street Dance - Olympic Games</p><a href="javascript:void(0)" onclick="downloadFile('DanceYear5.zip',<?php echo $this->level?>)">Download resource (.zip)</a></span>
                    </div>
                   
                    
                </td>
                <td id="resources_right_section" valign="top" class="vindent_right">
                    <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?php echo  $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                    </div>
               </td>
            </tr>
        </table>
    </div>
    <div id="status_bar" style="display:none;"></div>
