<? if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?}?>
<!--<div id="staffroom_welcome">
        <div id="staffroom_welcome_content">
            <span>Hi
                    <?php if ($this->level==0){?>
                        <a href='javascript:void(0)'><b><?php echo $this->username?></b></a>, you are visiting</span>
                    <?php }
                    elseif (($this->level>=1)&&($this->level<=5)) {?>
                        <a href='javascript:void(0)' onclick="javascript:editUser(<? echo $this->id?>)"><b><? echo $this->username?></b></a>, you are signed in</span>
                       <?php }
                       else {?>
                        <a href='/tplan/DB_Maintenance'><b><? echo $this->username?></b></a>, you are signed in</span>
            <?php }?>
            <?php if (($this->level>=5)){?>
            <div id="badge_staffroom">
                <a href="/staffroom"><span>Back to the PEplanning Staffroom</span></a>
            </div>
            <?}?>
            </div>
    </div>--> 
<div id="resources">
        <table class="stage">
            <tr>
                <td colspan="3">
                    <div class="resources_backlink"><a href="/resources"><span>back to Additional Resources</span></a></div>
                    <div id="resources_title">
                        <div id="resources_img_title_festival"><span>Long Term Guidance Plan</span></div>
                        <div id="resources_subtitle"><span>Our sports festival resources are guides to delivering intra-school sports festivals. Each festival guide includes information on how to organise the festival and a set of weekly sport specific plans that can be delivered to pupils to prepare them to take part in the festival.</span></div>
                    </div>
                </td>
            </tr>
            <tr>
                <td id="resources_left_section" valign="top">                    
                    <a id="resources_img_festivals_saf" class="resources_img_display"><span>Long Term Plan Guidance</span></a>
                    <a id="resources_img_festivals_athletics" class="resources_img_display"><span>Athletics</span></a>
                    <a id="resources_img_festivals_gym" class="resources_img_display"><span>Gymnastics</span></a>
                    <a id="resources_img_festivals_ttennis" class="resources_img_display"><span>Table Tennis</span></a>                                        
                    <a id="resources_img_festivals_netball" class="resources_img_display"><span>Netball Plan Guidance</span></a>
                    <a id="resources_img_festivals_rounders" class="resources_img_display"><span>Rounders Plan Guidance</span></a>
                </td>
                <td id="left_section_spacing"></td>
                <td id="middle_section" valign="top">
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle">Year 1 Speed, Agility and Quickness (SAQ) Festival Plans</span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('Y1SAQ.zip',<?php echo $this->level?>)">Download resources (.zip)</a></span>
                    </div>
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle"><a href="<? // link to pdf ?>" alt="click to view 'Long Term Plan Guidance'" title="click to view 'Long Term Plan Guidance'">Year 2 Athletics Festival Plans</a></span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('Y2Athletics.zip',<?php echo $this->level?>)">Download resources (.zip)</a></span>
                    </div>
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle"><a href="<? // link to pdf ?>" alt="click to view 'Long Term Plan Guidance'" title="click to view 'Long Term Plan Guidance'">Year 3 Gymnastics Festival Plans</a></span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('Y3Gymnastics.zip',<?php echo $this->level?>)">Download resources</a></span>
                    </div>
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle"><a href="<? // link to pdf ?>" alt="click to view 'Long Term Plan Guidance'" title="click to view 'Long Term Plan Guidance'">Year 4 Table Tennis Festival Plans</a></span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('Y4TableTennis.zip',<?php echo $this->level?>)">Download resources</a></span>
                    </div>
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle"><a href="<? // link to pdf ?>" alt="click to view 'Long Term Plan Guidance'" title="click to view 'Long Term Plan Guidance'">Year 5 Netball Festival Plans</a></span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('Y5Netball.zip',<?php echo $this->level?>)">Download resources</a></span>
                    </div>
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle"><a href="<? // link to pdf ?>" alt="click to view 'Long Term Plan Guidance'" title="click to view 'Long Term Plan Guidance'">Year 6 Rounders Festival Plans</a></span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('Y6Rounders.zip',<?php echo $this->level?>)">Download resources</a></span>
                    </div>
                </td>
                <td id="resources_right_section" valign="top" class="vindent_right">
                    <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                    </div>
               </td>
            </tr>
        </table>
    </div>
    <div id="status_bar" style="display:none;"></div>
