<?php if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?php }?>
<div id="resources">
        <table class="stage">
            <tr>
                <td colspan="3">
                    <div class="resources_backlink"><a href="/resources/additional-lesson-plans/"><span>back to Additional Lesson Plans</span></a></div>
                    <div id="resources_title">
                        <div id="resources_img_title_foundation"></div>
                    </div>
                </td>
            </tr>
            <tr>
                <td id="resources_left_section" valign="top">                    
                    <a id="resources_img_handball" class="resources_img_display"><span>Foundation - Throwing And Catching</span></a>
                </td>
                <td id="left_section_spacing"></td>
                <td id="middle_section" valign="top">
                    <div class="resources_mydisplay">
                        <p><span class="resources_midsection_subtitle">Foundation - Throwing And Catching</span></p>
                        <span class="resources_midsection_desc"><p></p><a onclick="downloadFile('ThrowingAndCatching.zip',<?php echo $this->level?>)">Download Lesson Plans (.zip)</a></span>
                    </div>
                    
                </td>
                <td id="resources_right_section" valign="top" class="vindent_right">
                    <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?php echo  $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                    </div>
               </td>
            </tr>
        </table>
    </div>
    <div id="status_bar" style="display:none;"></div>
