<div class="learn_content">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_left_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->left_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->left_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->left_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?php echo  $this->left_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->left_box_title[$i]?></span></a></div>
                            </div> 
                            <?php }?>
                        </div> 
                    </td>
                
                    <td valign="top" style="padding-left:30px; padding-right:30px;">
                        <h2>Prices and Services</h2>
                        <h3>Subscription Costs:</h3>
                        <h3>PEschool</h3>
                        <table id="peschool_subscription_table">
                            <tr>
                                <td class="table_header">School Size</td><td class="table_header" style="width:170px;">Annual Subscription Cost</td>
                            </tr>
                            <tr>
                                <td class="desc">1 - 300 pupils on roll</td>
                                <td class="prices">&pound;120</td>
                            </tr>
                            <tr>
                                <td class="desc">301 - 500 pupils on roll</td>
                                <td class="prices">&pound;195</td>
                            </tr>
                            <tr>
                                <td class="desc">500+ pupils on roll</td>
                                <td class="prices">&pound;245</td>
                            </tr>
                            <tr>
                                <td class="desc">Single Class</td>
                                <td class="prices">&pound;60</td>
                            </tr>
                        </table>
                        <p>To subscribe to PE School <a href="https://<?php echo $_SERVER['HTTP_HOST']?>/auth/payment"> Click Here</a></p>
                        <h3>PEcoach</h3>
                        <p>PEcoach is a flexible subscription and costs will reflect the coach or coaching organisation requirements. Quotations are available upon request</p>
                        <p>Email to <a href="mailto:info@peplanning.org.uk">info@peplanning.org.uk</a> or telephone 01535 644777</p>
                        <p><i>For PEschool and PEcoach subscriptions an invoice will be raised when all user accounts have been set up and payment is due 21 days after the invoice date</i></p>
                    </td>
                    <td id="right_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?php echo  $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div> 
                            <?php }?>
                        </div> 
                    </td>
                </tr>
            </table>
        </div>
