<?php 
if ($_SERVER['SERVER_PORT'] != '443') {
  header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
  }
$google_fonts="https://fonts.googleapis.com/css?family=Anaheim|Ubuntu:400,500|Cantarell|Raleway:200,400,600,800|Julius+Sans+One|Open+Sans:400,600";
$site_css="/css/newsite.css?".time();
$main_js="/js/main.js?".time();
$alerts_js="/js/jquery.alerts.js?".time();
$jq_tools_js="/js/jquery.tools.min.js?".time();
$jq_crypt_js="/js/jquery.jcryption.min.js?".time();
$jq_js="/js/jquery-1.8.2.min.js?".time();
$jq_ui_js="/js/jquery-ui-1.8.24.min.js?".time();
echo $this->doctype();
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Delivering high quality teaching resources, for Primary School PE');
$this->headLink()->prependStylesheet($google_fonts);
$this->headLink()->prependStylesheet($this->baseUrl().$site_css);
$this->headScript()->appendFile($this->baseUrl().$jq_js);
$this->headScript()->appendFile($this->baseUrl().$jq_ui_js);
$this->headScript()->appendFile($this->baseUrl().$jq_tools_js);
$this->headScript()->appendFile($this->baseUrl().$jq_crypt_js);
$this->headScript()->appendFile($this->baseUrl().$alerts_js);
$this->headScript()->appendFile($this->baseUrl().$main_js);
?>
<html>
    <head>
        <!-- meta tag for safari mobile -->
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <meta name="viewport" content="width=1200" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headMeta(); ?>  
        <?php echo $this->headScript(); ?>

<?php if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?php }?>
    </head>
    <body>
        <div class='wrapper'>
        <!--<div class='sm-header' id='top'>
	
            	<a href='http://peplanning.tumblr.com/'><img src="/img/icons/tumblr_logo_blue_32.png" border="0" /></a>
                
                <a href='https://twitter.com/PEplanning'><img src="/img/icons/Twitter-Bird-32-no-circle.png" border="0" /></a>
            
            	<a href='https://www.youtube.com/user/peplanning'><img src="/img/icons/YouTube-32-no-circle.png" border="0" /></a>
            
            	<a href='http://www.pinterest.com/peplanning/'><img src="/img/icons/Pinterest-32-no-circle.png" border="0" /></a>
            
            	<a href='https://www.facebook.com/PEplanning'><img src="/img/icons/Facebook-32-no-circle.png" border="0" /></a>
            
        </div>-->
        
            
            <div id='content-space'>
        	<?php echo $this->layout()->content; ?>
            </div>
        
        </div>
    </body>
</html>
