<div id="menu">
    <table id="stage" class="stage" align="center" border="0">
        <tr>
            <td id="logo"></td>
            <td class="divider"></td>
            <td id="item1"><a href="#">About us</a></td>
            <td class="divider"></td>
            <td id="item2">Plan a lesson</td>
            <td class="divider"></td>
            <td id="item3">Staff room</td>
            <td class="divider"></td>
            <td id="item4">Contact Us</td>
            <td class="divider"></td>
            <td id="item5"><a href="#"/></td>
        </tr>
    </table>
</div>

<div id="main_feature">
    <!-- tabs work as navigator for scrollable -->
        <div width="100%">
            <div style="float:left"><img src="/img/feature_arrow_blank.png" id="arrow_left" class="custom prev"/></div>
            <div style="float:right;"><img src="/img/feature_arrow_blank.png" id="arrow_right" onclick="alert('it works')" class="custom next"/></div>
        </div>
    <!-- panes -->
        <div id="flowpanes">
        <!-- wrapper for scrollable items -->
            <div class="items" style="left:-910px; top:5px;">
                <div id="panel1">
                    <table border="0" id="menu1">
                        <tr>
                            <td valign="top" >
                                <div class="panel_content">
                                    <p><img src="../images/icon_arrow.png">&nbsp;&nbsp;Functional with Desktop and iPad.</p>
                                    <p><img src="../images/icon_arrow.png">&nbsp;&nbsp;Reduces time spent on administration.</p>
                                    <p><img src="../images/icon_arrow.png">&nbsp;&nbsp;Generate reports into Excel and PDF formats.</p>
                                    <p><img src="../images/icon_arrow.png">&nbsp;&nbsp;Property and Enquiry data feed to website.</p>
                                    <br />
                                    <br />
                                    <br />
                                    <a href="/products/"><img src="../images/btn_overlay.png" class="btn_peap" /></a>
                                </div>
                            </td>
                        </tr>
                    </table>
                 </div>
                <div id="panel1">
                    <table border="0" id="menu2">
                        <tr>
                            <td valign="top" >
                                <div class="panel_content">                                    
                                    <a href="/services/"><img src="../images/btn_overlay.png" class="btn_support" /></a>
                                </div>
                            </td>
                        </tr>
                    </table>
                 </div>
                 <div id="panel1">
                    <table border="0" id="menu3">
                        <tr>
                            <td valign="top" >
                                <div class="panel_content" align="justify">
                                    <p>PE Planning is an educational tool ensuring the children in your school get the best opportunity to receive quality PE lessons and achieve their potential in sport.</p>
                                    <p>Through carefully constructed lesson plans, that are easy to follow, these plans are designed to keep all children fully involved in the learning process, engaged and challenged in a fun way.</p>
                                    <br />
                                    <br />
                                    <a href="/products/"><img src="../images/btn_overlay.png" class="btn_pep" /></a>
                                </div>
                                <br clear="all">
                            </td>
                        </tr>
                    </table>
                 </div>                 
             </div>
          </div>
     </div>















<div id="bluesky">
    <div id="slides">

    </div>
    <div id="videoplayer">
        <div id="videoplayer_title"></div>
        <div id="videoplayer_content"></div>
        <div id="videoplayer_footer">
            <p id="videoplayer_text"><a href="#">Try creating a lesson plan for free?</a></p>
        </div>
    </div>
    <div id="register_btn"></div>
</div>
<div id="grass"></div>
<div id="products">
    <table id="product_content" class="stage">
        <tr>
            <td id="peschool">
                <div id="peschool_content">
                    <p class="panel_header">For the entire school to enjoy all the benefits of PEplanning</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <p id="peschool_learnmore"><a href="#"><span>learn more</span></a></p>
                </div>
            </td>
            <td id="peteacher">
                <div id="peteacher_content">
                    <p class="panel_header">The personal option for the teacher to use with their class</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <p id="peteacher_learnmore"><a href="#"><span>learn more</span></a></p>
                </div>
            </td>
            <td id="pecoach">
                <div id="pecoach_content">
                    <p class="panel_header" style="text-align:left;">For the professional coach delivering physical education in primary schools</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <p id="pecoach_learnmore"><a href="#"><span>learn more</span></a></p>
                </div>
            </td>
        </tr>
    </table>
</div>
<div id="sitemap">
    <table id="sitemap_content" class="stage">
        <tr>
            <td class="sitemap_section">National Curriculum</td>
            <td class="sitemap_section">Example Plans</td>
            <td class="sitemap_section">Assistance</td>
            <td class="sitemap_section">Partners</td>
        </tr>
        <tr>
            <td><a href="http://www.education.gov.uk/schools/teachingandlearning/curriculum/primary">Current NCPE Key stage 1</a></td>
            <td><a href="#">Gymnastics Level 1/2</a></td>
            <td><a href="#">Prices and Services</a></td>
            <td><a href="">5-a-day-tv</a></td>
        </tr>
        <tr>            
            <td><a href="http://www.education.gov.uk/schools/teachingandlearning/curriculum/primary">Current NCPE Key stage 2</a></td>
            <td><a href="#">Tennis Level 2</a></td>
            <td><a href="#">Contact Us</a></td>
            <td><a href="http://www.sportsuk.org.uk/">Sports UK</a></td>
        </tr>
        <tr>
            <td><a href="http://www.education.gov.uk/">Department for Education (DfE)</a></td>
            <td><a href="#">Hockey Level 2/3</a></td>
            <td></td>            
            <td><a href="http://top100teachersites.com/">Top 100 Teacher sites</a></td>
        </tr>
        <tr>
            <td><a href="http://www.education.gov.uk/aboutdfe/armslengthbodies/a00200461/qcda">QCDA</a></td>
            <td><a href="#">Rounders Level </a></td>
            <td></td>
            <td><a href="http://www.itfacilitas.co.uk">IT Facilitas</a></td>            
        </tr>
        <tr>
            <td></td>
            <td><a href="#">Athletics Level 3/4</a></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td><a href="#">Football Level 4</a></td>
            <td></td>
            <td></td>
        </tr>        
    </table>    
</div>
<div id="contact">
    <div id="contact_content" class="stage">
        <table id="contact_form" border="0">
            <tr>
                <td id="form_title"/>
            </tr>
            <tr>
                <td><p>If there is something you want to know more about, and can’t find it on our website, please contact us by filling your details below and we’ll be in touch shortly.  You can also contact us through the following methods.</p></td>
            </tr>
        </table>
        <table id="contact_twitter" border="0">
            <tr>
                <td id="twitter_title"/>
            </tr>
            <tr>
                <td>
                    tweet box goes here
                </td>
            </tr>
        </table>
    </div>
</div>
<div id="footer_ruleoff">
    <div id="footer_ruleoff_content" class="stage">
        <div id="copyright">Copyright © 2012 PE Planning. All rights reserved.&nbsp;<!--<a href="#">Terms of Use</a>--></div>
    </div>
</div>
<div id="footer">
    <table border="0" id="footer_content" class="stage">
        <tr>
            <td id="footer_text">
                <p>Home &nbsp;|&nbsp; About Us &nbsp;|&nbsp; Register &nbsp;|&nbsp; Plan a Lesson &nbsp;|&nbsp; Staff Room &nbsp;|&nbsp; Contact</p>
                <p><b>PE Planning</b> &nbsp;Unit E, Hawkcliffe Works, Hebden Road, Oxenhope, West Yorkshire, BD22 9SY &nbsp; Tel. +44 (0) 1535 644777 &nbsp; &nbsp;Email. <a href="mailto:matt@peplanning.org.uk">matt@peplanning.org.uk</a></p>
            </td>
            <td id="itf_logo"><a href="http://www.itfacilitas.co.uk"><span>itfacilitas</span></a></td>
        </tr>
    </table>
</div>

