<? if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?}?>
<div class="learn_content">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_left_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->left_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->left_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->left_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->left_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->left_box_title[$i]?></span></a></div>
                            </div> 
                            <?php }?>
                        </div> 
                    </td>
                    <td valign="top" id="learn_text" style="margin-left:20px;">
                        <div id="content">
                            <div id="learn_content">
                                <div id="endorsements">
                                    <table id="endorsements_content">
                                        <tr>
                                            <td valign="top">
                                                <div>
                                                    <h2>Contact Us</h2>
                                                    <p>You may find you have questions regarding particular aspects of PEplanning and wish to contact someone specifically. Below we have highlighted our areas of support to ensure we deal with your enquiry effectively</p>
                                                    <p>General Enquiries</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="mailto:matt@peplanning.org.uk">matt@peplanning.org.uk</a><br /><br />
                                                    <p>Sales Enquires</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="mailto:matthew.dykes@peplanning.org.uk">matthew.dykes@peplanning.org.uk</a><br /><br />
                                                    <p>Resource Support</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="mailto:richard.logan@peplanning.org.uk">richard.logan@peplanning.org.uk</a><br /><br />
                                                    <p>IT Support</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="mailto:steve@peplanning.org.uk">steve@peplanning.org.uk</a><br /><br />

                                                    <p>Or</p>

                                                    <p>Telephone Enquires:</p>
                                                    <p>All Enquires</p>
                                                    <p>01535 644 777</p>

                                                    <p>Also see our FAQ section for further information</p>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                       </div>
                    </td>
                    <td id="right_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div> 
                            <?php }?>
                        </div> 
                    </td>
                </tr>
            </table>
        </div>