<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
        <title>Plan</title>
        <style>
            @page { size: A4 landscape;margin: 2pt 2pt 2pt 2pt }
        </style>
    </head>
    <body>
        <?php print_r($this->title_detail)?><br>
            <?php print_r($this->lesson_detail_objectives)?><br>
                <?php print_r($this->lesson_detail_keywords)?><br>
                <?php print_r($this->lesson_detail_icts)?><br>
                <?php print_r($this->lesson_detail_citizenships)?><br>
                    <?php print_r($this->lesson_detail_numeracys)?><br>
                        <?php print_r($this->lesson_detail_risk_assessments)?><br>
    <TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0>
        <TR>
            <TD width=33%><img src="/img/logo_letterhead.jpg" border=none></TD>
            <TD WIDTH=5% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			Name :
		</TD>
            <TD WIDTH=12% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>
<?php echo $this->name?>
           "</TD>
            <TD WIDTH=5% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			School :
		</TD>
            <TD WIDTH=12% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>".
<?php echo $this->school?>
           "</TD>".
            //<TD width=33% align='right'><a href=\"send_pdf.php?file=".$file."&orientation=landscape\"><img src=\"../index_files/icon_printer.jpg\" border=none alt='create PDF file' title='create PDF file'></a><a href=\"/tplan/Lessons.php?unit_id=".$uow_id."&plan_type=".$plan_type."\"><img src=\"../index_files/icon_edit.jpg\" border=none alt='edit plan' title='edit plan'></a><a href=\"/tplan/main.php\"><img src=\"../index_files/icon_home.jpg\" border=none alt='return to start page' title='return to start page'></a></TD>
        "</TR>
    </TABLE>
<BR>
    <TABLE WIDTH=100% BORDER=1 BORDERCOLOR=\"#b7cc79\" CELLPADDING=0 CELLSPACING=0>
            <TR>
            	<TD WIDTH=10% style='background:#d2e0a9;font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			Topic
		</TD>
		<TD WIDTH=10% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>".
$_SESSION[$lesson_num]['mysubject'].
                "</TD>
                <TD WIDTH=5% style='background:#d2e0a9;font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			Level
		</TD>
		<TD WIDTH=2% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>".
$_SESSION[$lesson_num]['level'].
                "</TD>
		<TD WIDTH=5% style='background:#d2e0a9;font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			Theme
		</TD>
		<TD WIDTH=20% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>".
$_SESSION[$lesson_num]['theme'].
		"</TD>
                <TD WIDTH=5% style='background:#d2e0a9;font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			Title
		</TD>
		<TD WIDTH=48% style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>".
$_SESSION[$lesson_num]['title'].
                "</TD>
		
	</TR>
<!--	<TR>
	<TD WIDTH=10% style='background:#d2e0a9;font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:bold;'>
			Learning Objectives
	</TD>
	<TD WIDTH=86% COLSPAN=7 VALIGN=TOP style='font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10px;font-weight:normal;'>";
        $objectives_string="<ol style='margin-left: -20px;#display:inline;#margin-left: 0px'>";
        while (list ($objective_id,$objective)=mysql_fetch_array($_SESSION[$lesson_num]['objectives']))
		{
                    $objectives_string=$objectives_string."<li>".$objective."</li>";
                }
                $objectives_string=$objectives_string."</ol>";
$summaryContent=$summaryContent.$objectives_string.
		"</TD>
	</TR>-->
    </TABLE>    
    </body>
</html>