<? if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?}?>
<div class="learn_content" style="margin-bottom:200px;">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_left_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->left_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->left_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->left_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->left_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->left_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                        </div>
                    </td>
                    <td valign="top" id="learn_text" style="margin-left:20px;">
                        <div id="legacy-content">

                            <table class="legacy-width">
                                <tr>
                                    <td id="legacy_main">
                                        <div id="legacy_title"><span>Continuing the Olympic Legacy London 2012</span></div>
                                    </td>
                                    <td id="legacy_right">
                                        <div id="legacy_callnow">01535 644 777</div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <div class="my-rule"/>
                                    </td>                                    
                                </tr>                            
                                <tr>
                                    <td valign="top" style="display:inline-block; padding-right:15px;">
                                        <div id="legacy-intro" class="mystyle">Build on this year’s successful summer of sport by inspiring your pupils with our Olympic Legacy package.</div>
                                        <div style="margin-top:10px;"class="mystyle-normal"><b>PEplanning</b> have teamed up with <b>Sports (UK)</b> to provide schools an Olympic Legacy Programme</div>
                                        <!--<div style="margin-top:20px;"class="my-rule"/>-->
                                        <div style="margin-bottom:20px;" class="mystyle-normal"><p>When you subscribe to the PEplanning Olympic Legacy Programme you will receive an Olympic based unit of work to help you inspire the next generation of Olympians in addition to 1 years full access to PEplanning.</p></div>

                                        <div class="legacy-subtitle">What's in the Olympic Legacy Package?</div>
                                        <div style="margin-top:10px;"class="my-rule"/>
                                        <div class="mystyle-normal">
                                            <div><span></span></div>
                                            <ul style="font-size:16px; line-height:32px;">

                                                <li style="color:#26bcb9; font-weight:bold;">One year subscription to PEplanning</li>
                                                <li style="color:#e33194;"><span style="font-weight:bold;">Sports (UK)’s Olympic Resource, that includes:</span>
                                                    <ul>
                                                        <li style="color:#e33194;">Creative curriculum resources</li>
                                                        <li style="color:#e33194;">PE lesson plans</li>
                                                        <li style="color:#e33194;">Sports Day/Week Guidance</li>
                                                        <li style="color:#e33194;">Organising Committee and Games Maker Resources</li>
                                                        <li style="color:#e33194;">Cheerleading lesson plans</li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            



                                            <br />

                                            <p>For more information please call Matthew: <b>01535 644 777</b> or email him at <a href="mailto:matt@peplanning.org.uk"><b>matt@peplanning.org.uk</b></a></p>
                                            
                                        </div>

                                    </td>
                                    <td valign="top">
                                        <div id="legacy_inspire-box">
                                            <p>Contact PEplanning today to receive your Olympic Legacy Package and help inspire a generation.</p>
                                            <p style="margin-top:30px;">Call: <b style="color:#666;">01535 644 777</b> or</br>
                                                Email: <a href="mailto:matt@peplanning.org.uk"><b>matt@peplanning.org.uk</b></a>
                                            </p>

                                        </div>
                                        <div>
                                            <div align="left" class="mystyle-normal" id="legacy-subtitle">It all starts at Primary School...</div>
                                            <div id="legacy-hc"/>
                                            <div class="mystyle-normal" id="legacy-hc-text">                                                
                                                <!--<p>"PE Planning is a fantastic tool which will ensure that all the children in your school will get an opportunity to receive quality PE lessons and achieve their potential in sport"</p>-->
                                                
                                                <p>Helen is a 2 times Olympic athlete, current European 3000M Champion and current 3000M Steeplechase British record holder</p>
                                                <p style="font-size:14px; font-weight:bold;">"I was lucky to be inspired by my Primary School teacher, Frank Green, to start running as an 8 year old he set me on a pathway which has been the focus of my life, to become a champion athlete and to compete for my country."</p>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </table>                           
                                
                                
                            </div>                         
                      
                    </td>
                    
                </tr>
            </table>
        </div>



