<? if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?}?>
<div class="learn_content">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_left_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->left_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->left_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->left_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->left_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->left_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                        </div>
                    </td>
                    <td valign="top" id="learn_text" style="margin-left:20px;">
                        <div id="content">
                            <div id="learn_content">
                                <div id="slide_1_more">
                                    <table id="slide_1_more_content">
                                        <tr>
                                            <td valign="top">
                                                <h2>PEplanning helps teachers in schools...</h2>
                                                <div class="my-rule">
                                                <p>Our online service has been created to support Primary Schools with their planning and delivery of Physical Education. It allows teachers to quickly and effectively take care of their PE lesson planning. Our carefully designed lesson plans allow teachers to deliver a range of PE topics with confidence.</p>
                                                <h2>Our Service</h2>
                                                <div class="my-rule">
                                                <p>We provide an expanding service covering a range of Physical Educational support:</p>
                                                <ul>
                                                    <li>National Curriculum linked</li>
                                                    <li>eg. Create and print Units of work</li>
                                                    <li>eg. Printed assessment tables</li>
                                                    <li>These need to be factual things that the user can see or have in their hand .</li>
                                                    <li>(If they get to this point they're showing signs of interest) move them on to subscribing for free!</li>
                                                </ul>
                                                <p>To see how PEplanning can support your schools Physical Education provision</p><a href="javascript:void(0)" onclick="javascript:showOverlay('Register');">Register free</a>
                                                <h2>What Schools say about PEplanning</h2>
                                                <div class="my-rule">
                                                    <ul>
                                                        <li>Find appropriate endoresments and recomendations</li>
                                                    </ul>
                                                <p><a href="/createaplan">Try creating a lesson plan</a> or <a href="javascript:void(0)" onclick="javascript:showOverlay('Register');">Register free</a></p>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                       </div>
                    </td>
                    <td id="right_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

