<? if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?}?>
<div class="learn_content">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_left_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->left_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->left_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->left_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->left_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->left_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                        </div>
                    </td>
                    <td valign="top" id="learn_text" style="margin-left:20px;">
                        <div id="content">
                            <div id="learn_content">
                                <div id="slide_2_more">
    <table id="slide_2_more_content">
        <tr>
            <td valign="top">
                <h2>Helen Clitheroe</h2>
                <p class="">Helen is a 2 times Olympic Athlete, the current European 3000M Champion and the current 3000M Steeplechase British record holder</p>
                <p>"PE Planning is a fantastic tool which will ensure that all the children in your school will get an opportunity to receive quality PE lessons and achieve their potential in sport"</p>
                <p>"I was lucky to be inspired by my Primary School teacher, Frank Green, to start running as an 8 year old he set me on a pathway which has been the focus of my life, to become a champion athlete and to compete for my country."</p>
                <p>To find out more about Helen Clitheroe visit her <a href="http://www.helenclitheroe.com">website</a></p>
                <p><a href="/learn/endorsements">Click here to see what else people are saying about PEplanning</a></p>
                <h2>Our Service</h2>
                <p>We provide much more that creating high quality lesson plans. We provide an ever growing service that covers a range of Physical Educational support:</p>
                <ul>
                    <li>Create your own, specific PE lesson plans</li>
                    <li>Tailor plans to meet your exact requirements</li>
                    <li>Extra-curricular support </li>
                    <li>Constantly updated with new resources</li>
                </ul>
                <p>To see how PEplanning can support your schools Physical Education provision</p><a href="javascript:void(0)" onclick="javascript:showOverlay('Register');">Register Here for free</a>
                <h2>Why choose PEplanning?</h2>
                <ul>
                    <li>The most comprehensive PE resource available</li>
                    <li>A flexible, tailorable approach to lesson planning</li>
                    <li>National Curriculum linked</li>
                    <li>Progression and Differentiation throughout</li>
                </ul>
                <p><a href="/createaplan">Try it yourself</a> or <a href="javascript:void(0)" onclick="javascript:showOverlay('Register');">register</a></p>
            </td>
        </tr>
    </table>
</div>
                            </div>
                       </div>
                    </td>
                    <td id="right_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_right_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->right_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->right_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->right_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->right_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->right_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                        </div>
                    </td>
                </tr>
            </table>
        </div>


 