<?php if($_SERVER['HTTP_HOST'] == 'www.peplanning.org.uk') {?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31237723-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?php }?>
<div class="learn_content" style="margin-bottom:200px;">
            <table>
                <tr>
                    <td id="left_section" valign="top">
                        <div id="my_boxes">
                            <?php for($i=1;$i<=$this->num_left_boxes;$i++){?>
                            <div id="<?php echo "box_".$this->left_box_title[$i]?>" class="promobox">
                                <div class="box_content">
                                    <div id="<?php echo "box_".$this->left_box_title[$i]."_content"?>">
                                    </div>
                                </div>
                            <div id="<?php echo "box_".$this->left_box_title[$i]."_title"?>" class="promotitle"><a onclick="boxAction('<?echo $this->left_box_title[$i]?>')" class="box_link"><span>learn more about the <?php echo $this->left_box_title[$i]?></span></a></div>
                            </div>
                            <?php }?>
                        </div>
                    </td>
                    <td valign="top" id="learn_text" style="margin-left:20px;">
                         <!--<ul class="youtube-videogallery">
                         </ul>
                                  <script>
                                      $(document).ready(function(){
                                      $("ul.youtube-videogallery").youtubeVideoGallery({
                                          apiFallbackUrl: 'http://www.youtube.com/user/peplanning/videos',
                                          apiUrl: 'http://gdata.youtube.com/feeds/api/users/peplanning/uploads?alt=json'
                                          });
                                      });
                                  </script> -->
                         <?php
                              
                              foreach ($this->videoFeed as $videoEntry) {
                              echo "<iframe width='320' height='240' src='//www.youtube.com/embed/".$videoEntry->getVideoId()."?rel=0' frameborder='0' allowfullscreen></iframe>";
                              
                              }
                         ?>
                    </td>
                </tr>
            </table>
        </div>
