<div class="editplan-wrapper">
<!-- classnames for the pages should include: 1) type of page 2) page name-->
  <div class="s-page random-restored-page">
    <h2 class="page-title">Some minimized App</h2>
    <div class="close-button s-close-button">x</div>
  </div>
  <div class="s-page custom-page">
    <h2 class="page-title">Thank You!</h2>
    <div class="close-button s-close-button">x</div>
  </div>
  <div class="r-page random-r-page">

    <div class="page-content">
      <h2 class="page-title">App Screen</h2>
      <p></p>
    </div>
    
    <div class="close-button r-close-button">x</div>
  </div>
<!--each tile should specify what page type it opens (to determine which animation) and the corresponding page name it should open-->
  <div class="dashboard clearfix">
    <ul class="tiles">
      <div class="col1 clearfix">
        <li class="tile tile-2xbig tile-1 slideTextUp" data-page-type="r-page" data-page-name="random-r-page">
          <div><p>What is<br>PE Planning?</p></div>
          <div><p>Primary School<br>PE Lesson Plans</p></div>
        </li>
        <li class="tile tile-2xbig tile tile-2 slideTextRight" data-page-type="s-page" data-page-name ="random-restored-page">
          <div><p>Watch our<br>helpful video guides</p></div>
          <div><p>How do I use<br>PE Planning</p></div>
        </li>
        </div>

      <div class="col2 clearfix">
        <li class="tile tile-2xbig tile-3 slideTextUp" data-page-type="r-page" data-page-name="random-r-page">
          <div><p>Plan a lesson</p></div>
          <div><p>create your own<br>PE lesson for free</p></div>
        </li>
        <li class="tile tile-2xbig tile-4 slideTextLeft" data-page-type="r-page" data-page-name="random-r-page">
          <div><p>blank tile</p></div>
          <div><p>Put something in here</p></div>
        </li>
       
      </div>

      <div class="col3 clearfix">      
        <li class="tile tile-big tile-5  slideTextUp" data-page-type="custom-page" data-page-name="random-r-page">
           <div><p>staffroom</p></div>
          <div><p>edit and print your stored plans</p></div>
        </li>
       <li class="tile tile-big tile-6 slideTextUp" data-page-type="custom-page" data-page-name="random-r-page">
           <div><p>subscribe for free</p></div>
          <div><p>in 5 minutes you could be using PE planning</p></div>
        </li>
        <li class="tile tile-big tile-7 slideTextUp" data-page-type="custom-page" data-page-name="random-r-page">
           <div><p>contact us</p></div>
          <div><p>want to know more and can't find the answer?</p></div>
        </li>
        <li class="tile tile-big tile-8 slideTextUp" data-page-type="custom-page" data-page-name="random-r-page">
           <div><p>about us</p></div>
          <div><p>more information about PE planning</p></div>
        </li>
      </div>
    </ul>
  </div><!--end dashboard-->